INSERT INTO `movies` (`MovieID`, `MovieName`, `MovieYear`) VALUES (NULL, 'Black Panther', '2018');
INSERT INTO `movies` (`MovieID`, `MovieName`, `MovieYear`) VALUES (NULL, 'Avengers End Game', '2019');
DELETE FROM `movies` WHERE MovieName = "Black Panther"
INSERT INTO `movies` (`MovieID`, `MovieName`, `MovieYear`) VALUES (NULL, 'Black Panther', '2018');
INSERT INTO `movies` (`MovieID`, `MovieName`, `MovieYear`) VALUES (NULL, 'Avengers End Game', '2019');